//
//  HealthReport.swift
//  mac-health
//
//  Created by Matt on 22/08/2026.
//

import Foundation

// Represents the complete health report generated by mac-health.
struct HealthReport: Codable {
  let device: DeviceInfo
  let storage: StorageInfo?
  let memory: MemoryInfo
  let battery: BatteryInfo?
  let security: SecurityInfo
  let softwareUpdates: SoftwareUpdateInfo
  let users: [UserInfo]
}
